### ISSUE TITLE
Still having issues, can't download version 1.1.2

### ISSUE THREAD

**Issue by z3nth10n** [DRKV333/ShopExpander#2]
I don't know why, when downloading ShopExpander with tModLoaader 0.11.4 this file is downloading:

[ShopExpander.zip](https://github.com/DRKV333/ShopExpander/files/3525489/ShopExpander.zip)

Instead of:

[ShopExpander.zip](https://github.com/DRKV333/ShopExpander/files/3525491/ShopExpander.zip)

Note: Replace zip extension by tmod

**Comment by z3nth10n** [comment]
I reverse engineered the code from the tModLoader: https://github.com/tModLoader/tModLoader/blob/c9cead627625c3c9383ec0d6e92663f78ddb4b37/patches/tModLoader/Terraria.ModLoader.Core/TmodFile.cs#L348

Modifying the first 32 bytes (4 bytes for TMOD + 8 bytes for ReadString and the next 20 bytes for the Hash), and everything works well again. (I used the [tmod file from here](https://github.com/DRKV333/ShopExpander/releases/download/v1.1.2/ShopExpander.tmod) and modified it, using the one provided by the tModLoader)

This is the modified file: 

[ShopExpander-Mod.zip](https://github.com/DRKV333/ShopExpander/files/3525671/ShopExpander-Mod.zip)

**Comment by DRKV333** [comment]
Could you elaborate on what the actual issue is here? Is the .tmod file not getting read by 0.11 correctly?
I've downloaded Shop Expander from the mod browser, and it appears to be downloading the correct thing. Shop Expander v1.1.2 build using tModLoader 0.10. That first file you linked looks a bit like what you'd get after 0.11 upgrades the .tmod file to the latest format revision. Which is a perfectly normal thing that tModLoader does.

**Comment by DRKV333** [comment]
Well, I have no idea what I should be doing about this, so I'm just gonna close the issue. Feel free to reopen if there still is problem.
